### ISSUE TITLE
Example of function `create_attachment`

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-samples#18]
Hi (and Happy New Year),

I am working on improving the examples for `create_attachment` functions and related functionalities (e.g. add attachment to step or retrieving list of attachments for a Test Case).

Could you tell me actually what is the `stream` for the `create_attachment` function?
```python
    def create_attachment(self, upload_stream, project=None, file_name=None, upload_type=None, area_path=None):
        """CreateAttachment.
        Uploads an attachment.
        :param object upload_stream: Stream to upload
        ...
        """
```

I tried both solutions below but none seems to work:

```python
with open('./smiley.png', "rb") as f:
    binary_content = bytes(f.read())
attachment = client_wit.create_attachment(binary_content, project, 'smiley.png')
```

```python
attachment = client_wit.create_attachment("Hello my friend", project, 'test6.txt')
```
(this solution creates a text file but it contains the double quotes in the text)

Thanks

**Comment by vtbassmatt** [comment]
I'm not sure. That would be a better question for the folks at https://github.com/microsoft/azure-devops-python-api

**Comment by jfthuong** [comment]
already did before... :)
https://github.com/Microsoft/azure-devops-python-api/issues/155#issuecomment-451839494
