### ISSUE TITLE
Add support of Azure DevOps version 5.0 / 5.1

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-samples#20]
Module `vsts` for VSTS / TFS has been replaced by `azure-devops`  (https://github.com/Microsoft/azure-devops-python-api) with versions 5.0 and 5.1 of the API.

The code has been reworked; for example, the following:
```python
from vsts.vss_connection import VssConnection
connection = VssConnection(base_url=team_instance, creds=credentials)
core_client = connection.get_client('vsts.core.v4_0.core_client.CoreClient')
```

has been replaced by:

```python
from azure.devops.connection import Connection
connection = Connection(base_url=organization_url, creds=credentials)
core_client = connection.clients.get_core_client()
```

It should be considered to have both versions available in the example (and set via a variable in the configuration). Or at least the latest version.

**Comment by vtbassmatt** [comment]
This is important. I just don't know when I'll have time to work on it myself.

Here's what I'd propose: I'll move the `vsts`-based examples to a branch, in case they need updates in the future. Then `master` can start adopting the new `azure.devops` approach.
