### ISSUE TITLE
Sample for create test run and update test run result for particular test-points 

### ISSUE THREAD

**Issue by WIINAI-KKUMAR** [microsoft/azure-devops-python-samples#24]
Firstly Thanks for you support and effort . 

I am started understanding version 5.1. It bit difficult to understand method as there no sample for the most of method. 
Request here is, Do we have any documentation on how to use method in packages. like (pandas or flask). ? If Yes Could you please share us that documentation link.
if no, Could you please help us on this to method and usages especially on "Test"

**Comment by vtbassmatt** [comment]
The [Python API](https://github.com/microsoft/azure-devops-python-api/) has a pretty easy-to-follow "getting started" sample right in the README. I haven't tried integrating with Flask or Pandas, but between the samples here and that getting started guide, it should be straightforward.

**Comment by WIINAI-KKUMAR** [comment]
Hi Team,

we have followed that document. We haven't found related to TEST related document.

It would be very helpful if could share that document.

Thanks,
Vinaykumar
________________________________

**Comment by vtbassmatt** [comment]
I see, sorry. You can take a look at the REST API docs [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs?view=azure-devops-rest-5.1), and then it's relatively straightforward to translate that to the Python API.
